# Error management

Error management is a fundamental aspect of building robust and observable applications, and it should be as important as any other part of a codebase. In Go, error management doesn't rely on the traditional try/catch mechnism as most programming languages do. Instead errors are returned as normal return values.e

## Panicking

In Go, panic is a built-in function that stops the ordinary flow:

```go
func main() {
    fmt.Println("a")
    panic("foo")
    fmt.Println("b")
}
```

This code prints a and then stops before printing b:

```txt
a
panic: foo

goroutine 1 [running]:
main.main()
    main.go:7 +0xb3
```

Once a panic is triggered, it continues up the call stack until either the current goroutine has returned or panic is caught with recover:

```go
func main() {
    defer func() {
        if r := recover(); r != nil {
            fmt.Println("recover", r)
        }
    }()

    f()
}

func f() {
    fmt.Println("a")
    panic("foo")
    fmt.Println("b")
}
```

In the f function, once panic is called, it stops the current execution of the function and goes up the call stack: main. In main, because the panic is caught with recover, it doesn't stop the goroutine.

```txt
a
recover foo
```

Note that calling recover() to capture a goroutine panicking is only useful inside a defer function; other wise, the function would return nil and have no other effect. This is because defer functions are also executed when the surrounding function panics. 

```go
func checkWriteHeaderCode(code int) {
    if code < 100 || code > 999 {
        panic(fmt.Sprintf("invalid writeHeader code %v", code))
    }
}
```

This function panics if the status code is invalid, which is a pure programmer error.

Another example based on a programmer error and be found in the database/sql package while registering a database driver:

```go
func Register(name string, driver driver.Driver) {
    driversMu.Lock()
    defer driversMu.UnLock()
    if driver == nil {
        panic("sql: Register driver is nil")
    }
    if _, dup := drivers[name]; dup {
        panic("sql: Register called twice for driver " + name)
    }
    drivers[name] = driver
}
```

Panicking in Go should be used sparingly. We have seen two prominent cases, one to signal a programmer error and another where our application fails to create a mandatory dependency. Hence, there are exceptional conditions that lead us to stop the application. In most other cases, error management should be done with a function that returns a proper error type as the last return argument.

## 49 .Ignore when to wrap an error

Since Go 1.13 the %w directive allows to to wrap errors conveniently. But some developers may be confused about when to wrap an error (or not). So, let's remind ourselves what error wrapping is and then when to use it. 

Error wrapping is about wrapping or packing an error inside a wrapper container that also makes the source error available. The two main use cases for error wrapping are the following: 

- Adding additional context to an error
- Making an error as a specific error

We receive a request from a specific user to access a database source, but we get a permission denied error during the query. For debuggine purposes, if the error is eventually logged, we want to add extra context.

```go
err := errors.New("permission denied")
wrapper := fmt.Errorf("When user X tried to access resource Y %w", err)
```

Now let's say that instead of adding context, we want to mark the error. For example, we want to implement an HTTP handler that checks whether all the errors received while calling functions are of a Forbidden type so we can return a 403 status code. In that case, we can wrap this error inside Forbidden

```go
err := errors.New("permission denied")
wrapper := fmt.Errorf("Forbidden %w", err)
```

In both cases, the source remains available. Hence, a caller can also handle an error by unwrapping it and checking the source error. Also note that sometimes we want to combine both approaches: **adding context and marking an error.**

```go
func main() {
	fmt.Println(Foo())
}

func Foo() error {
	err := errors.New("permission denied")
	if err != nil {
		return BarError{err} // err is wrapped inside BarError
	}
	return nil
}

// Before Go 1.13, to wrap an error, the only option without using an external library was to create a custom error type
type BarError struct {
	Err error
}

func (b BarError) Error() string {
	return "bar failed:" + b.Err.Error()
}
```

The benefit of this option is its flexibility. Because BarError is a custom struct, we can add any additional context if needed. However, being obliged to create a specific error type can quickly become cumbersome if we want to repeat this operation.

To overcome this situation, Go 1.13 introduced the %w directive.

```go
if err != nil {
    return fmt.Errorf("bar failed: %w", err)
}
```

This code wraps the source error to additional context without having to create another error type.

Because the source error of remains available, a client can unwrap the parent error and then check whether the source error was of a specific type or value.

The last option we will discuss to the use the %v directive

```go
if err != nil {
    return fmt.Errorf("bar failed: %v", err)
}
```

The difference is that the error itself isn't wrapped. We transform it into another error to and context, and the source error is no longer available.

The information about the source of the problem remains available. However, a caller can't unwrap this error and check whether the source was bar error. So, in a sense, this option is more restrictive than %w.

To make sure our clients don't rely on something that we consider implementation details, the error returned should be transformed, not wrapped. 

|Option|Extra context|Marking an error|Source error available|
|-|-|-|-|
|Returning error directly|No|No|Yes|
|Custom error type|Possible|Yes|Possible|
|fmt.Errorf with %w|Yes|No|Yes|
|fmt.Errorf|Yes|No|No|

To summarize, when handling an error, we can decide to wrap it. Wrapping to about adding additional context to an error and/or marking an error as a specific type. If we need to mark an error, we should create a custom error type. However, if we just want to add extra context, we should use fmt.Errorf with the %w directive as it doesn't require creating a new error type. Yet, error wrapping creates potential coupling as it makes the source error available for the caller. If we want to prevent it, we shouldn't use error wrapping but error transformation, for example, using fmt.Errorf with the %v directive. 
